services:
  web:
    build: 
      context: ./api/app
      dockerfile: Dockerfile
    command: sh -c "export FLASK_APP=app && python -m debugpy --listen "0.0.0.0:5678" -m flask --debug run -h 0.0.0.0 -p 5000"
    volumes:
      - ./api/data:/data
      - ./api/app:/app
    restart: on-failure
    ports:
      - 5000:5000
    deploy:
      resources: 
      # não usar esses limites de recurso no deployment final,
      # se esse é o deployment final e a aplicação estiver travando
      # remova os limites de recurso
        limits:
          cpus: '1.5'
          memory: 1G
        reservations:
          cpus: '1'
          memory: 250M